export class BankDetailsBean{
  micr : any;
  branch : any;
  address : any;
  state : any;
  contact : any;
   upi : any;
   rtgs : any;
   city : any;
   center : any;
   district : any;
   neft : any;
   imps : any;
   swift : any;
   iso3166 : any;
   bank : any;
   bankcode : any;
   ifsc : any;
}
